version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: alpino-db-user
      POSTGRES_PASSWORD: rrwFsWHV
      POSTGRES_DB: alpino-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
